# for local dev environment
version: "3.8"
services:
  as-gateway:
    build:
      context: .
    restart: always
    environment:
    - REDIS_HOST=redis
    - REDIS_PASS=
    - RABBIT_HOST=rabbit
    - RABBIT_USER=guest
    - RABBIT_PASS=guest
    - APP_PORT=8080
    - LOG_LEVEL=debug
    depends_on:
    - rabbit
    - redis
    container_name: as-gateway

  rabbit:
    image: rabbitmq:3.5.6
    ports:
      - "5672:5672"
    expose:
      - 5672
      - 15672
  redis:
    image: redis:5.0.5-alpine
    restart: always
    ports:
      - '6379:6379'
    expose:
      - '6379'
